### ISSUE TITLE
Bugs n' Shit

### ISSUE THREAD

**Issue by BenJarrett** [nss-evening-cohort-14/clown-college-dashboard-clown-college-dashboard#21]
Overall - Dani
- [x]  When the Navbar is clicked, it redirects the user to the Students Page
- [x] Fix Authentication
- [x] Refresh issues (Nathan)
- [x] When a user is not logged in and the user is redirected to a page, the buttons will pop up for a hot second. 

Majors 
- [x] Make Majors 'Read Only' when not logged in - Nathan
- [x] Says all Clown lessons at top of Majors Page
- [x] When the Add Major button is clicked, it says 'Add Lesson' 
- [x] When the delete button is clicked, it does not delete and it displays the error "majorEvents.js?c984:30 Uncaught (in promise) TypeError: Cannot read property 'name' of null
    at eval (majorEvents.js?c984:30)"

Students
- [x] When user adds a student, both 'Edit and Delete' buttons disappear until it is refreshed.
- [x] When the user adds a student, it adds a duplicate 
- [x] No Edit function on Students page
- [x] User created Students cannot be deleted. Error "studentEvents.js?81e7:17 Uncaught (in promise) TypeError: Cannot read property 'fullName' of null
    at eval (studentEvents.js?81e7:17)"

Teachers 
- [x] No delete Functionality - Sara

Classes 
- [x] When a user submits the add lesson form, it will not submit. It gives an error of "classEvents.js?97cb:38 The event add-submit is not accounted for"

**Comment by danicrosby** [comment]
User can now login and start on a landing page

#37
