### ISSUE TITLE
Create Data Flow Diagram

### ISSUE THREAD

**Issue by BenJarrett** [nss-evening-cohort-14/clown-college-dashboard-clown-college-dashboard#28]

**Comment by danicrosby** [comment]
[](https://lucid.app/lucidchart/66395ef9-9b5c-4b36-9bc7-bf094a80db06/edit?beaconFlowId=EA2CA4A849E1EA78&page=0_0#)

![Clown College Workflow Diagram](https://user-images.githubusercontent.com/68397076/114272990-f90af880-99dd-11eb-9889-d1552afadb23.png)
