### ISSUE TITLE
Add Screenshots

### ISSUE THREAD

**Issue by BenJarrett** [nss-evening-cohort-14/clown-college-dashboard-clown-college-dashboard#31]

**Comment by danicrosby** [comment]
![Screen Shot 2021-04-14 at 8 41 53 PM](https://user-images.githubusercontent.com/68397076/114803608-5f3ca600-9d65-11eb-9fcf-6cbdeada34e4.png)

**Comment by danicrosby** [comment]
![Screen Shot 2021-04-14 at 9 08 01 PM](https://user-images.githubusercontent.com/68397076/114803674-81362880-9d65-11eb-9042-c67e31c02b8c.png)

**Comment by danicrosby** [comment]
![Screen Shot 2021-04-14 at 9 08 25 PM](https://user-images.githubusercontent.com/68397076/114803704-901cdb00-9d65-11eb-9ceb-3cf9484f2934.png)

**Comment by danicrosby** [comment]
![Screen Shot 2021-04-14 at 9 09 27 PM](https://user-images.githubusercontent.com/68397076/114803780-b773a800-9d65-11eb-8a8e-3a1e652312b9.png)

**Comment by danicrosby** [comment]
![Screen Shot 2021-04-14 at 9 09 59 PM](https://user-images.githubusercontent.com/68397076/114803808-c9554b00-9d65-11eb-962e-c63fe1a62095.png)
